[package]
name = "pipe"
version = "0.0.1"
authors = ["York Xiang <bombless@126.com>"]

[dependencies.winapi]
git = "https://github.com/retep998/winapi-rs"

[dependencies.kernel32-sys]
git = "https://github.com/retep998/winapi-rs"
